name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:   
      - uses: actions/checkout@v2
        
      - name: Setup Bazelisk
        uses: bazelbuild/setup-bazelisk@v1.0.1
        
      - name: Run Kotlin tests
        run: |
          echo Running Kotlin tests... 
          bazelisk test //src/kotlin/...
        
      - name: Run Java tests
        run: |
          echo Running Java tests...
          bazelisk test //src/java/...

      - name: Run Python tests
        run: |
          echo Running Python tests...
          bazelisk test //src/python/...

      - name: Setup Swift
        uses: fwal/setup-swift@v1

      # - run: export CC="clang"

      - name: Run Swift tests
        run: |
          echo Running Swift tests...
          bazelisk test //src/python/...