name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v2
      
      - uses: fwal/setup-swift@v1
        
      - name: Setup Bazelisk
        uses: bazelbuild/setup-bazelisk@v1.0.1
        
      - name: Run tests
        run: |
          CC="clang"
          echo CC
          export CC="clang"
          echo CC
          bazelisk test //...
