name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check-out repository
        uses: actions/checkout@v2
        
      - name: Setup Bazelisk
        uses: bazelbuild/setup-bazelisk@v1.0.1
        
      - name: Run tests
        run: |
          CC="clang"
          bazelisk test //...
